### ISSUE TITLE
Bug in positioning algorithm

### ISSUE THREAD

**Issue by erlebach** [nickchen120235/walker-python#1]
Hi, 

When trying your algorithm on one of my graphs (where IDs are strings), I found an error on line 337 of `walker.py`. 
More specifically, I get a division by zero because `left_siblings=0`. This occurs, because the following `while` construct is not entered: 
```while temp and temp is not neighbor_ancestor:```

My question whether Walker's algorithm always has a solution? 

Here is the section of your code where the problem occurs. If you send me your email, I can email you two dataframes with my graph. 

A secondary question would be whether the configuration parameters have to be chosen carefully to make sure that the algorithm produces a viable solution. Before running your algorithm, I made sure that all the siblings were set correctly. I did this manually. Thanks for any insight!

```python 
      # Find the distance and apply it to curr's subtree
      # Add appropriate portions to smaller interior subtrees
      distance = neighbor.prelim + left_mod_sum + self.config['TREE_SEPARATION'] + self.config['NODE_SIZE'] - (leftmost.prelim + right_mod_sum)
      if self.debug: print(f'[_apportion] distance: {distance}')
      if distance > 0:
      # Count interior sibling subtrees in LeftSiblings
        left_siblings = 0
        temp = curr
        if self.debug: print(f'[_apportion] temp: {temp.id}, neighbor_ancestor: {neighbor_ancestor.id}')
        while temp and temp is not neighbor_ancestor:
          left_siblings += 1
          temp = temp.left_sibling
          if self.debug: print(f'[_apportion] temp: {temp.id if temp else None}, neighbor_ancestor: {neighbor_ancestor.id}, left_siblings: {left_siblings}')

        if temp:
        # Apply portions to appropriate leftsibling subtrees
          proportion = distance / left_siblings
          temp = curr
          while temp is not neighbor_ancestor:
            if self.debug: print('[_apportion] temp is not neighbor_ancestor')
            temp.prelim += distance
            temp.modifier += distance
            distance -= proportion
            temp = temp.left_sibling
        else:
          return
      ### end of distance > 0 ###
```

**Comment by nickchen120235** [comment]
Thanks for the report. You can send the dataset to `nickchen120235 [AT] gmail [DOT] com`

I'll looking into it when I have time.
